[package]
name = "minifb-frontend"
version = "0.1.0"
authors = ["Eric Nowac <nowace@msoe.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gba-emulator = {path = "../gba-emu"}
minifb = "0.15.3"